package Vistas;

import Controladores.ControladorJuego;


public class PanelDatos extends javax.swing.JPanel {

    private final ControladorJuego controlador;
    
    public PanelDatos(ControladorJuego c) {
        initComponents();
        controlador = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOponente = new javax.swing.JLabel();
        lblApuesta = new javax.swing.JLabel();
        btnApostar = new javax.swing.JButton();
        lblJugador = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtApuesta = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(750, 70));
        setLayout(new java.awt.GridLayout(2, 4, 3, 3));

        lblOponente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOponente.setText("ESPERANDO A OTRO JUGADOR...");
        lblOponente.setAlignmentX(0.5F);
        add(lblOponente);

        lblApuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApuesta.setText("$-----");
        add(lblApuesta);

        btnApostar.setText("Apostar");
        btnApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostarActionPerformed(evt);
            }
        });
        add(btnApostar);

        lblJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugador.setText("ESPERANDO A OTRO JUGADOR...");
        add(lblJugador);

        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setText("$-----");
        add(lblSaldo);

        txtApuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApuesta.setText("0");
        add(txtApuesta);
    }// </editor-fold>//GEN-END:initComponents

    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostarActionPerformed
        controlador.apostar(Float.parseFloat(txtApuesta.getText()));
    }//GEN-LAST:event_btnApostarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JLabel lblApuesta;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblOponente;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtApuesta;
    // End of variables declaration//GEN-END:variables

    public void refreshDatos(String jugador, String oponente, float saldo, float apuesta) {
       lblJugador.setText("Jug.: " + jugador);
       lblOponente.setText("Op.: " + oponente);
       lblSaldo.setText("Saldo: $" + saldo);
       lblApuesta.setText("Apuesta: $" + apuesta);
    }


    public void deshabilitar() {
        btnApostar.setEnabled(false);
    }
    
    public void habilitar() {
        btnApostar.setEnabled(true);
    }

}
