/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorUserLogin;
import Dominio.Juego;
import Dominio.Juego.Eventos;
import Dominio.Jugador;
import java.util.Observable;

/**
 *
 * @author Owner
 */
public class VentanaNivel extends javax.swing.JFrame {

    /**
     * Creates new form VentanaNivel
     */
    
    private ControladorUserLogin controlador;
    private Jugador jugador;
    
    public VentanaNivel(Jugador j) {
        initComponents();
        controlador = new ControladorUserLogin();
        jugador = j;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNivelBajo = new javax.swing.JButton();
        btnNivelMedio = new javax.swing.JButton();
        btnNivelAvanzado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elija el tamaño de su Buscaminas:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 40, 250, 40);

        btnNivelBajo.setText("Nivel Bajo");
        btnNivelBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelBajoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNivelBajo);
        btnNivelBajo.setBounds(140, 100, 110, 30);

        btnNivelMedio.setText("Nivel Medio");
        btnNivelMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelMedioActionPerformed(evt);
            }
        });
        getContentPane().add(btnNivelMedio);
        btnNivelMedio.setBounds(140, 160, 110, 30);

        btnNivelAvanzado.setText("Nivel Avanzado");
        btnNivelAvanzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelAvanzadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNivelAvanzado);
        btnNivelAvanzado.setBounds(140, 220, 110, 30);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNivelMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelMedioActionPerformed
        // TODO add your handling code here:
        ingresar(Juego.Eventos.Medio);
    }//GEN-LAST:event_btnNivelMedioActionPerformed

    private void btnNivelBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelBajoActionPerformed
        // TODO add your handling code here:
        ingresar(Juego.Eventos.Bajo);
    }//GEN-LAST:event_btnNivelBajoActionPerformed

    private void btnNivelAvanzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelAvanzadoActionPerformed
        // TODO add your handling code here:
        ingresar(Juego.Eventos.Avanzado);
    }//GEN-LAST:event_btnNivelAvanzadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNivelAvanzado;
    private javax.swing.JButton btnNivelBajo;
    private javax.swing.JButton btnNivelMedio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void ingresar(Eventos o) {
        new VentanaJuego(jugador,o).setVisible(true);
    }
}
