/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorReplayJuego;
import Controladores.VistaReplayJuego;
import Dominio.ICasillero;
import Dominio.Juego;
import java.awt.GridLayout;
import java.awt.ScrollPane;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Owner
 */
public class VentanaReplayJuego extends javax.swing.JFrame implements VistaReplayJuego{

   private ControladorReplayJuego controlador;
    private PanelControlReplay panelControl;
    private JPanel panelFichas;
    
    public VentanaReplayJuego(Juego j) {
        initComponents();
        controlador = new ControladorReplayJuego(j);
        JPanel panel = (JPanel) getContentPane();
        panel.setLayout(new GridLayout(2, 1));
        
        panelControl = new PanelControlReplay(controlador);
        panelFichas = new JPanel();
        
        ScrollPane scroll = new ScrollPane();
        scroll.add(panelFichas);
        
        panel.add(panelControl);
        panel.add(scroll);
        
        controlador.setVista(this);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 
       @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    @Override
    public void cargarDatos(String jugador, Date fecha, float apuesta, List<ICasillero> casilleros) {
        panelControl.cargarDatos(jugador, fecha, apuesta);
        cargarFichas(casilleros);
    }
    
    private void cargarFichas(List<ICasillero> casilleros) {
        panelFichas.removeAll();
        GridLayout layout = new GridLayout(1, casilleros.size());
        panelFichas.setLayout(layout);
        for (ICasillero c : casilleros) {
            BotonCasillero b = new BotonCasillero(c);
            panelFichas.add(b);
        }
        revalidate();
        repaint();
    }

    @Override
    public void cargarHora(Date d) {
        panelControl.cargarHora(d);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
