/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorReplayJuego;
import Controladores.VistaReplayJuego;
import Dominio.ICasillero;
import Dominio.Juego;
import java.awt.GridLayout;
import java.awt.ScrollPane;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author Owner
 */
public class VentanaReplayJuego extends javax.swing.JFrame implements VistaReplayJuego {

    private ControladorReplayJuego controlador;
    private PanelControlReplay panelControl;
    private Juego juego;

    JSplitPane split;

    public VentanaReplayJuego(Juego j) {
        initComponents();
        juego = j;
        controlador = new ControladorReplayJuego(j);

        panelControl = new PanelControlReplay(controlador);

        split = new JSplitPane();
        split.setTopComponent(new PanelTableroReplay(controlador));
        setContentPane(split);

        controlador.setVista(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    @Override
    public void cargarDatos(String jugador, float apuesta, List<ICasillero> casilleros) {
        panelControl.cargarDatos(jugador, apuesta);
        mostrarTablero(juego.getSize(), (ArrayList<ICasillero>) casilleros);
    }

    public void mostrarTablero(int tamaño, ArrayList<ICasillero> casilleros) {
        PanelTableroReplay p = new PanelTableroReplay(controlador);
        p.mostrar(tamaño, casilleros);
        split.setBottomComponent(p);
        validate();
        split.setDividerLocation(200);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
